# Generated by Django 2.2.3 on 2019-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_pic', models.CharField(max_length=1000)),
            ],
        ),
    ]
